# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier*"
          - "vite"
          - "*-plugin"
          - "*-loader"
          - "jest*"
          - "vitest*"
          - "@testing-library/*"
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
      frontend-dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier*"
          - "vite"
          - "*-plugin"
          - "*-loader"
          - "jest*"
          - "vitest*"
          - "@testing-library/*"
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
      frontend-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  # Backend dependencies
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      backend-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
