name: E2E Tests
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**"

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Svelocker UI Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: svelocker-ui:test
          outputs: type=docker,dest=/tmp/svelocker-ui.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: svelocker-ui-image
          path: /tmp/svelocker-ui.tar

  e2e-tests:
    needs: build
    permissions:
      contents: read
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout Svelocker UI Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: svelocker-ui-image
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/svelocker-ui.tar

      - name: Create Docker network
        run: docker network create svelocker-network

      - name: Run Svelocker UI container
        run: |
          docker run -d --name svelocker-ui \
            --network svelocker-network \
            -p 8080:8080 \
            -e PUBLIC_REGISTRY_URL=http://registry:5000 \
            -e PUBLIC_REGISTRY_NAME="Test Registry" \
            svelocker-ui:test

          # Wait for application to start
          sleep 10

          # Check if application is running
          curl -sSf http://localhost:8080 || (echo "Application failed to start" && exit 1)

          # Save logs in background
          docker logs -f svelocker-ui &> /tmp/backend.log &

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          PLAYWRIGHT: "true"

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: tests/.test-report
          include-hidden-files: true
          retention-days: 30

      - name: Upload backend logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-logs
          path: /tmp/backend.log
          retention-days: 15

      - name: Cleanup Docker containers
        if: always()
        run: |
          docker stop svelocker-ui registry || true
          docker rm svelocker-ui registry || true
          docker network rm svelocker-network || true
